#IPv6 disabled

#  - name: Disable ipv6
#    lineinfile:
#    #- backup: yes
#    - dest: /etc/sysctl.conf
#    - line: "{{ item }}"
#    with_items:
#    - "{{ net.ipv6.conf.all.disable_ipv6 = 1 }} "
#    - "{{ net.ipv6.conf.default.disable_ipv6 = 1 }} "
#    register: sysctl_ipv6
#
#  - name: Sysctl load
#    shell: sysctl --load
#    when: sysctl_ipv6|changed


- name: disable ipv6
  lineinfile:
    dest: /etc/sysctl.conf 
    line: "{{ item }}"
    backup: yes
  with_items:
  - "net.ipv6.conf.all.disable_ipv6 = 1"
  - "net.ipv6.conf.default.disable_ipv6 = 1"
  register: sysctl_ipv6

- name: sysctl load
  shell: sysctl --load
  when: sysctl_ipv6|changed
