- name: start firealld
  service:
    name: firewalld
    state: started

- name: stop firealld
  service:
    name: firewalld
    state: stopped

- name: restart chrony
  service:
    name: chronyd
    state: restarted
    enabled: yes
