---
#- name: Update yum
#  yum:
#    name: "*"
#    state: latest

- name: Install Common Packges
  yum:
    name: vim-enhanced
    state: latest

- name: Disable Firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Disable SELinux
  selinux:
    state: disabled
